### PR TITLE
Carrier Board Approval

### PR DESCRIPTION
**Pull request by Ankit300**

### CODE REVIEW

**Comment by Ankit300** [comment]
Approval required for carrier board.

**Comment by Hive-Michael** [comment]
Should this be linked to the ProfiCNC repo? https://github.com/proficnc/The-Cube/blob/master/CB_REV_C_Altium/Carrier%20board%20footprint%20approval

**Comment by Hwurzburg** [comment]
Sorry just now understood your comment @Hive-Michael ...will add link and close this soon

**Comment by Hwurzburg** [comment]
fixed....closing this one

**Pull request closed without merging**
