### PR TITLE
add files for esp32imu_module_v11 ArduPilot target

### PR DESCRIPTION
**Pull request by nkruzan**
available here: https://www.tindie.com/products/makerfabs/esp32-6-axis-imu-module/ (I'm not affiliated, and I purchased myself)

### CODE REVIEW

**Review by davidbuzz — APPROVED** [review]
lgtm

**Comment by Hwurzburg** [comment]
these are open to the public...if you got hem with a purchase, I would say no

**Comment by nkruzan** [comment]
they are from github, is open source project, just archiving here...was trying to be clear in that i'm not pushing these for my own gain, maybe should have worded differently 

as noted in the readme:
from: https://github.com/Makerfabs/ESP32_IMU_Module ( retrieved 4/4/2022)

**Comment by Hwurzburg** [comment]
okay...just checking...merging...thanks

**Pull request merged**
